### ISSUE TITLE
Import conflict depending on order between gdal <> fastkml

### ISSUE THREAD

**Issue by hyperknot** [cleder/fastkml#106]
I have the strangest bug with fastkml and osgeo.

The following works:
```
from osgeo import ogr
import fastkml
```

But if I swap the order I get a `ModuleNotFoundError: No module named '_gdal'`:
```
import fastkml
from osgeo import ogr
```

Nothing else needs to be in the script, just these 2 import lines.

Of course all the "optimize imports" IDE commands put the import line at the top, so it'll always break after unless I manually swap those lines.

Here is the full trace:
```
Traceback (most recent call last):
  File ".../venv/lib/python3.7/site-packages/osgeo/__init__.py", line 21, in swig_import_helper
    return importlib.import_module(mname)
  File "/Users/user/.pyenv/versions/3.7.11/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 670, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 583, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1043, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: dlopen(.../venv/lib/python3.7/site-packages/osgeo/_gdal.cpython-37m-darwin.so, 2): Symbol not found: _GEOSArea
  Referenced from: /usr/local/opt/libspatialite/lib/libspatialite.7.dylib
  Expected in: flat namespace
 in /usr/local/opt/libspatialite/lib/libspatialite.7.dylib

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./kml-icons.py", line 6, in <module>
    from osgeo import ogr
  File ".../venv/lib/python3.7/site-packages/osgeo/__init__.py", line 37, in <module>
    _gdal = swig_import_helper()
  File ".../venv/lib/python3.7/site-packages/osgeo/__init__.py", line 34, in swig_import_helper
    return importlib.import_module('_gdal')
  File "/Users/user/.pyenv/versions/3.7.11/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named '_gdal'
```

System:
- macOS Big Sur
- Python 3.7.11 from pyenv
- homebrew gdal
```
gdalinfo --version
GDAL 3.3.1, released 2021/06/28
```
- `pygdal==3.3.1.7`

**Comment by hyperknot** [comment]
I opened this issue in both projects:
https://github.com/nextgis/pygdal/issues/68

**Comment by cleder** [comment]
#137 drops native shapely support
