### ISSUE TITLE
Value Error on running Example scripts.

### ISSUE THREAD

**Issue by withoutwaxaryan** [cleder/fastkml#144]
When you try to run `examples/ReadKml.py` & `examples/UsageExamples.py`, the following error arises :

```
Traceback (most recent call last):
  File "UsageExamples.py", line 22, in <module>
    k.from_string(kmlFile.read())
  File "/home/aryan/anaconda3/lib/python3.7/site-packages/fastkml/kml.py", line 90, in from_string
    xml_string, parser=etree.XMLParser(huge_tree=True, recover=True)
  File "src/lxml/etree.pyx", line 3237, in lxml.etree.fromstring
  File "src/lxml/parser.pxi", line 1891, in lxml.etree._parseMemoryDocument
ValueError: Unicode strings with encoding declaration are not supported. Please use bytes input or XML fragments without declaration.
```

**Comment by martimpassos** [comment]
Hi, is the fix up on PyPi already? I'm getting the same error with 
```
with open("/content/001AAN005121.kml", 'rt', encoding="utf-8") as myfile:
  doc=myfile.read()
  k.from_string(doc)
```
Changing it to 
```
with open("/content/001AAN005121.kml", 'rt', encoding="utf-8") as myfile:
  doc=myfile.read()
  k.from_string(bytes(doc))
```
Gives `TypeError: string argument without an encoding`

**Comment by withoutwaxaryan** [comment]
Hi, the PR has been merged in develop branch, not the main one - so the fix isn't on PyPi.

Can you check if the changes in the [linked PR](https://github.com/cleder/fastkml/pull/145) works for you?

**Comment by martimpassos** [comment]
Yes I have done that and it works well, thanks!
